language: python

env:
    - MILESTONE=0
    - MILESTONE=50
    - MILESTONE=100

script:
  nosetests -A milestone<=$MILESTONE

matrix:
  allow_failures:
    - env: MILESTONE=50
    - env: MILESTONE=100
